theme: jekyll-theme-minimal
favicon: https://osmchina.oss-cn-beijing.aliyuncs.com/favicon_black.ico
logo: https://osmchina.oss-cn-beijing.aliyuncs.com/favicon_black.ico

url: "https://osmchina.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap